# -*- coding: utf-8 -*-
"""Probabilistic Machine Learning Murphy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wSqwejC-S4TDQm_WcefOJ8cgRAZITz6
"""

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import os
import seaborn as sns
import pandas as pd
import sklearn
from sklearn.datasets import load_iris

sns.set(style='ticks', color_codes=True)
pd.set_option('display.precision', 2)
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', 30)
pd.set_option('display.width', 100)

iris_data = load_iris()

X = iris_data.data
y = iris_data.target

df = pd.DataFrame(data=X, columns=iris_data.feature_names)
df['label'] = pd.Series(iris_data.target_names[y], dtype='category')

palette = { 'setosa': 'orange', 'versicolor': 'green', 'virginica': 'purple' }

g = sns.pairplot(df, vars=df.columns[0:4], hue='label', palette=palette)
plt.show()

iris_df = df.copy()
iris_df.columns = ['sl', 'sw', 'pl', 'pw'] + ['label']

g = sns.pairplot(iris_df, vars=iris_df.columns[0:4], hue='label')
plt.tight_layout()
plt.show()

sns.stripplot(x="label", y="sl", data=iris_df, jitter=True)
plt.show()